/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailsMediaIdIndexRouteImport } from './routes/details/$mediaId/index'
import { Route as DetailsMediaIdDownloadDownloadIdRouteImport } from './routes/details/$mediaId/download/$downloadId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsMediaIdIndexRoute = DetailsMediaIdIndexRouteImport.update({
  id: '/details/$mediaId/',
  path: '/details/$mediaId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsMediaIdDownloadDownloadIdRoute =
  DetailsMediaIdDownloadDownloadIdRouteImport.update({
    id: '/details/$mediaId/download/$downloadId',
    path: '/details/$mediaId/download/$downloadId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/details/$mediaId': typeof DetailsMediaIdIndexRoute
  '/details/$mediaId/download/$downloadId': typeof DetailsMediaIdDownloadDownloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/details/$mediaId': typeof DetailsMediaIdIndexRoute
  '/details/$mediaId/download/$downloadId': typeof DetailsMediaIdDownloadDownloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/search': typeof SearchRoute
  '/details/$mediaId/': typeof DetailsMediaIdIndexRoute
  '/details/$mediaId/download/$downloadId': typeof DetailsMediaIdDownloadDownloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/search'
    | '/details/$mediaId'
    | '/details/$mediaId/download/$downloadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/search'
    | '/details/$mediaId'
    | '/details/$mediaId/download/$downloadId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/search'
    | '/details/$mediaId/'
    | '/details/$mediaId/download/$downloadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SearchRoute: typeof SearchRoute
  DetailsMediaIdIndexRoute: typeof DetailsMediaIdIndexRoute
  DetailsMediaIdDownloadDownloadIdRoute: typeof DetailsMediaIdDownloadDownloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$mediaId/': {
      id: '/details/$mediaId/'
      path: '/details/$mediaId'
      fullPath: '/details/$mediaId'
      preLoaderRoute: typeof DetailsMediaIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$mediaId/download/$downloadId': {
      id: '/details/$mediaId/download/$downloadId'
      path: '/details/$mediaId/download/$downloadId'
      fullPath: '/details/$mediaId/download/$downloadId'
      preLoaderRoute: typeof DetailsMediaIdDownloadDownloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SearchRoute: SearchRoute,
  DetailsMediaIdIndexRoute: DetailsMediaIdIndexRoute,
  DetailsMediaIdDownloadDownloadIdRoute: DetailsMediaIdDownloadDownloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
